CREATE DATABASE SheGo;
GO
USE SheGo;
GO
CREATE TABLE users (id INT IDENTITY PRIMARY KEY, username NVARCHAR(50) NOT NULL UNIQUE, password_hash CHAR(64) NOT NULL, salt CHAR(32) NOT NULL, phone VARCHAR(20), role VARCHAR(20) NOT NULL DEFAULT 'USER', created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
CREATE TABLE products (id INT IDENTITY PRIMARY KEY, name NVARCHAR(100) NOT NULL, description NVARCHAR(500), price DECIMAL(10,2) NOT NULL, stock INT NOT NULL DEFAULT 0, image_url VARCHAR(500), created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
CREATE TABLE orders (id INT IDENTITY PRIMARY KEY, user_id INT NOT NULL REFERENCES users(id), total_amount DECIMAL(10,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PAID', delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING', created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
CREATE TABLE order_items (id INT IDENTITY PRIMARY KEY, order_id INT NOT NULL REFERENCES orders(id), product_id INT NOT NULL REFERENCES products(id), quantity INT NOT NULL, unit_price DECIMAL(10,2) NOT NULL);
INSERT INTO products(name,description,price,stock) VALUES (N'可乐',N'冰镇可乐',3.00,100),(N'泡面',N'宿舍速食',5.50,100),(N'抽纸',N'基础日用品',12.90,50);
-- 生产环境请通过注册页面创建账号；不要在脚本中写入真实密码。
